"""Unit tests for the PDF Situation Report generator."""

import sys
from pathlib import Path
from datetime import datetime, timezone

# Add 'src' to sys.path for local imports
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd
import pytest

from utils.pdf_report import (
    _get_top_events,
    generate_situation_report,
)


# ── Fixtures ──────────────────────────────────────────────────────────────────
@pytest.fixture(scope="module")
def sample_df() -> pd.DataFrame:
    """Build a realistic sample earthquake DataFrame."""
    return pd.DataFrame(
        {
            "place": [
                "10km NE of Tokyo",
                "15km SW of Kathmandu",
                "Off coast of Chile",
                "5km N of LA",
                "Near Fiji Islands",
            ],
            "magnitude": [5.2, 7.1, 6.3, 4.8, 3.5],
            "depth_km": [12.5, 35.0, 50.0, 8.0, 120.0],
            "main_time": [
                "2026-03-20T10:00:00Z",
                "2026-03-19T14:30:00Z",
                "2026-03-18T08:15:00Z",
                "2026-03-17T22:45:00Z",
                "2026-03-16T05:00:00Z",
            ],
            "alert_level": ["Yellow", "Red", "Orange", "Green", "Green"],
            "country": ["Japan", "Nepal", "Chile", "USA", "Fiji"],
            "tsunami": [0, 1, 1, 0, 0],
            "link": [
                "https://earthquake.usgs.gov/1",
                "https://earthquake.usgs.gov/2",
                "https://earthquake.usgs.gov/3",
                "",
                "",
            ],
        }
    )


@pytest.fixture(scope="module")
def sample_filters() -> dict:
    """Build a sample filters dictionary."""
    return {
        "source": "USGS",
        "start_date": "2026-03-16",
        "end_date": "2026-03-20",
        "min_mag": 3.0,
        "alerts": ["Green", "Yellow", "Orange", "Red"],
        "countries": ["Japan", "Nepal", "Chile", "USA", "Fiji"],
    }


@pytest.fixture(scope="module")
def timestamp() -> datetime:
    """Provide a fixed UTC timestamp."""
    return datetime(2026, 3, 20, 12, 0, 0, tzinfo=timezone.utc)


# ── Tests ─────────────────────────────────────────────────────────────────────
class TestGenerateSituationReport:
    """Tests for the main PDF generation function."""

    def test_returns_valid_pdf(
        self, sample_df: pd.DataFrame, sample_filters: dict, timestamp: datetime
    ) -> None:
        """Generated bytes should begin with the PDF magic number."""
        result = generate_situation_report(sample_df, sample_filters, timestamp)
        assert isinstance(result, bytes)
        assert result[:5] == b"%PDF-"

    def test_report_is_nonempty(
        self, sample_df: pd.DataFrame, sample_filters: dict, timestamp: datetime
    ) -> None:
        """Report should have substantial content (> 1KB)."""
        result = generate_situation_report(sample_df, sample_filters, timestamp)
        assert len(result) > 1024

    def test_report_with_empty_df(
        self, sample_filters: dict, timestamp: datetime
    ) -> None:
        """Report should still generate cleanly when DataFrame is empty."""
        empty_df = pd.DataFrame(
            columns=[
                "place",
                "magnitude",
                "depth_km",
                "main_time",
                "alert_level",
                "country",
                "tsunami",
                "link",
            ]
        )
        result = generate_situation_report(empty_df, sample_filters, timestamp)
        assert isinstance(result, bytes)
        assert result[:5] == b"%PDF-"

    def test_report_with_minimal_columns(
        self, sample_filters: dict, timestamp: datetime
    ) -> None:
        """Report should not crash when only bare-minimum columns are present."""
        minimal_df = pd.DataFrame(
            {
                "place": ["Somewhere"],
                "magnitude": [5.0],
                "alert_level": ["Green"],
            }
        )
        result = generate_situation_report(minimal_df, sample_filters, timestamp)
        assert isinstance(result, bytes)
        assert result[:5] == b"%PDF-"

    def test_report_with_nan_values(
        self, sample_filters: dict, timestamp: datetime
    ) -> None:
        """Report should handle NaN/missing values gracefully."""
        nan_df = pd.DataFrame(
            {
                "place": ["Unknown", None],
                "magnitude": [float("nan"), 4.5],
                "depth_km": [None, float("nan")],
                "main_time": [None, "2026-03-20T10:00:00Z"],
                "alert_level": ["Unknown", "Green"],
                "country": ["Unknown", "Japan"],
                "tsunami": [0, 0],
                "link": ["", ""],
            }
        )
        result = generate_situation_report(nan_df, sample_filters, timestamp)
        assert isinstance(result, bytes)
        assert result[:5] == b"%PDF-"

    def test_report_generates_fast(
        self, sample_df: pd.DataFrame, sample_filters: dict, timestamp: datetime
    ) -> None:
        """PDF generation should complete in under 2 seconds."""
        import time

        t0 = time.time()
        generate_situation_report(sample_df, sample_filters, timestamp)
        elapsed = time.time() - t0
        assert elapsed < 2.0, f"PDF generation took {elapsed:.1f}s (should be < 2s)"


class TestGetTopEvents:
    """Tests for the internal _get_top_events helper."""

    def test_returns_top_n(self, sample_df: pd.DataFrame) -> None:
        """Should return at most top_n events sorted by magnitude descending."""
        events = _get_top_events(sample_df, top_n=3)
        assert len(events) == 3
        mags = events["magnitude"].tolist()
        assert mags == sorted(mags, reverse=True)

    def test_returns_all_if_fewer_than_n(self, sample_df: pd.DataFrame) -> None:
        """Should return all events when total < top_n."""
        events = _get_top_events(sample_df, top_n=100)
        assert len(events) == len(sample_df)

    def test_top_event_is_highest_magnitude(self, sample_df: pd.DataFrame) -> None:
        """The first event should have the highest magnitude."""
        events = _get_top_events(sample_df, top_n=1)
        assert events.iloc[0]["magnitude"] == 7.1

    def test_empty_df_returns_empty(self) -> None:
        """Should return empty DataFrame for empty input."""
        empty = pd.DataFrame(columns=["place", "magnitude", "depth_km", "main_time"])
        events = _get_top_events(empty)
        assert events.empty